add styles and markup in files list-catalog
DmytroZhdanov/project-DP_UNITED pull request #13
Opened 2023-06-09 00:32 UTC by Tanyusha7

2023-06-09 08:12 UTC, DmytroZhdanov requested changes

2023-06-09 08:12 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +    <ul class="films-catalog"></ul>
Краще буде задати клас "catalogue-films-list" або ж "catalogue-movies-list"
Я більше схиляюся до слова movie(s) аби на всіх сторінках було однакове слово
І додайте, будь ласка, дата-атрибут для того, аби в майбутньому ми через скрипт рендерили всередині цього списку лішки

2023-06-09 08:12 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +    <div class="target-element"></div>
Змініть, будь ласка, клас на більш описовий, аби краще було зрозуміло, що саме це за дів. Також додайте, будь ласка, дата-атрибут для скрипта.
Пропишіть ще всередині цього діва шаблони розмітки для кнопок пагінації. Там, здається два варіанти має бути. Додайте їм класи, що я написав Вам в особисті і доповніть стилі вже у файлі зі стилями для вашої секції

2023-06-09 08:12 UTC, DmytroZhdanov commented on src/css/pages/catalogue/list-catalogue.css
По стилях поки не буду детально перевіряти, але поки помітив, що кнопка пошуку дивно себе поводить під час ховеру, перевірте, будь ласка

2023-06-09 23:14 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +            <input
це допишу пізніше

2023-06-09 23:17 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +              name="searchFilm"
ок

2023-06-09 23:21 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +    <h1 class="visually-hidden">Catalog</h1>
Діма, я думаю це не принципово, в слові Сatalog помилки немає.

2023-06-09 23:23 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +      <form class="catalog-search-form" id="catalog-search-for">
ок

2023-06-09 23:24 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +          <input
з інпутом розібралися

2023-06-09 23:24 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +          <svg class="icon-search" width="18" height="18">
вони більші ніж потрібні, тому стилі перезаписані

2023-06-09 23:28 UTC, Tanyusha7 commented on src/partials/list-catalogue.html
> +    <div class="target-element"></div>
кнопки пагінації йдуть в бібліотеці, дата-атрибути пізніше

2023-06-10 07:31 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +    <h1 class="visually-hidden">Catalog</h1>
Це для того аби всюди було однакове написання цього слова

2023-06-10 07:31 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +            <input
Прийнято

2023-06-10 07:34 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +          <svg class="icon-search" width="18" height="18">
Розмір іконки змінюється на десктопі з 18х18 на 20х20. Підправте, будь ласка, тоді розміри цієї іконки у файлі стилів кнопок

2023-06-10 07:35 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +    <div class="target-element"></div>
Прийнято

2023-06-10 08:32 UTC, DmytroZhdanov reviewed
По слову Сatalog, залишаємо його. Потім я підправлю у всіх інших місцях, аби було так само, як у Вас))
Якщо ви хочете, оновити свою гілку, давайте я закоментую ваші файли, аби вони нічого не зламали, та змержу? А ви потім створите собі нову гілку і продовжите працювати. Що ви думаєте?

2023-06-10 08:32 UTC, DmytroZhdanov commented on src/partials/list-catalogue.html
> +      <form class="catalog-search-form" id="data-catalog-search-form">
У вас клас "catalog-search-form" повторюється у формі та ц огортаючому діві. Ви так і планували.
Якщо Id ви писали для джс, то дата-атрибут пишеться інакше. Замість id="data-catalog-search-form" напишіть просто data-catalog-search-form. Без лапок, без нічого

2023-06-11 19:25 UTC, DmytroZhdanov approved these changes

2023-06-11 19:25 UTC, merged