Create Library Hero
DmytroZhdanov/project-DP_UNITED pull request #25
Opened 2023-06-10 15:57 UTC by Cherydens

2023-06-10 21:36 UTC, DmytroZhdanov requested changes
Зірочки я виправив. Там буквально одну властивість треба було дописати до одного правила в стилях. Аби перестрахуватися позадавав висоту на контейнер з класом, який я казав прописати. Доречі клас був не той, що я казав. Підправив ще розмітку, огорнув у додатковий дів.

2023-06-10 21:43 UTC, DmytroZhdanov commented
Загалом, треба підправити трохи розмітку, а саме додати тег h1, відрефакторити стилі як написав в коментарях, та відрефакторити джс (підправити назви функцій, рейсів, можливо ще щось. Аби в назвах не було main чи library, бо це розділення вже не потрібно). Після виконання вищезазначеного, додатково детально перевірю всі цсс правила і, якщо все буде чудово, то буду мержити.
Дуже гарна робота, дякую!)

2023-06-11 09:43 UTC, Cherydens commented
Все зробив згідно коментарів. Додав два файли розмітки hero-commons.css та hero-markup.css. Додав їх до styles.css.

2023-06-11 12:54 UTC, DmytroZhdanov approved these changes

2023-06-11 12:54 UTC, merged